### PR TITLE
stop locking

### PR DESCRIPTION
**Pull request by CUKESIM**

### CODE REVIEW

**Comment by cukesimfan** [comment]
pls dont lock again,cukesim whats ur discord bbg i forgot

**Comment by asdaeshndj** [comment]
wtf

**Comment by CUKESIM** [comment]
i quit discord

**Comment by cukesimfan** [comment]
fuck off minecraft pfp
ur clapped af

**Comment by CUKESIM** [comment]
who is [asdaeshndj](https://github.com/asdaeshndj)

**Comment by cukesimfan** [comment]
what do u use then??
guilded?

**Comment by nopliers** [comment]
???/

**Comment by CUKESIM** [comment]
no i dont use any chat app

**Comment by cukesimfan** [comment]
bro fucking add me on windows live messenger rn

**Comment by gabe-12** [comment]
fecal matter

**Comment by cukesimfan** [comment]
yo u got blackberry messenger???

**Comment by CUKESIM** [comment]
i do use facebook to talk to my grandma though

**Comment by CUKESIM** [comment]
isnt blackberry old

**Comment by gabe-12** [comment]
i got skype

**Comment by cukesimfan** [comment]
fr? add me on facebook daddyyyy 😩

**Comment by CUKESIM** [comment]
my facebook is secret

**Comment by prtzls** [comment]
Yall who wanna play portal

**Comment by gabe-12** [comment]
add me on facebook >> https://grabify.link

**Comment by cukesimfan** [comment]
NAH NAH ADD ME ON FACEBOOK DADDY

**Comment by CUKESIM** [comment]
thats a obvious ip logger

**Comment by cukesimfan** [comment]
TELL ME YOUR FACEBOOK CUKESIM

**Comment by gabe-12** [comment]
cukesimisanigga

**Comment by cukesimfan** [comment]
FR DADDY HOWD YOU KNOW IT WAS AN IP LOGGER? GOD DAMN UR SO SMARTT DADDYY

**Comment by kineryy** [comment]
I have heavy doubts that this is the real CUKESIM, not sure what's making it obvious

**Comment by CUKESIM** [comment]
my facebook is secret stop asking

**Pull request closed without merging**
